version: "3"
services:

  server:
    container_name: outside-server-container
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        OUTSIDE_SERVER_IGNORE_DATABASE_ERRORS: ${OUTSIDE_SERVER_IGNORE_DATABASE_ERRORS}
    ports:
      - "8082:8080"
    image: outside-server-image
    restart: always
    depends_on:
      - database
    labels:
      - traefik.http.routers.server.rule=Host(`${SERVER_DNS}`)
    networks:
      - proxy
      - outside

  database:
    container_name: outside-database-container
    ports:
      - 5432:5432
    image: postgres:14.2
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres-container-data:/var/lib/postgresql/data
    labels:
      - traefik.http.routers.db.rule=Host(`${DB_DNS}`)
    networks:
      - proxy
      - outside

networks:
  proxy:
    external: true
  outside:
    driver: bridge